/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfaceAdopterAnimal.java
 *
 * Created on 26 févr. 2014, 13:22:58
 */
package sos;

import Dao.AnimalDAO;
import Entities.Animal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amal
 */
public class InterfaceAdopterAnimal extends javax.swing.JFrame {

    /** Creates new form InterfaceAdopterAnimal */
    public InterfaceAdopterAnimal() {

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtableanimal = new javax.swing.JTable();
        scrollPane1 = new java.awt.ScrollPane();
        jLabel1 = new javax.swing.JLabel();
        ButtonAdopter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jtableanimal.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jtableanimal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtableanimal.setName("jtableanimal"); // NOI18N
        jScrollPane1.setViewportView(jtableanimal);

        scrollPane1.setName("scrollPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sos.SOSApp.class).getContext().getResourceMap(InterfaceAdopterAnimal.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        ButtonAdopter.setName("ButtonAdopter"); // NOI18N
        ButtonAdopter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAdopterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addComponent(ButtonAdopter)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonAdopter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // lors de l'ouverture de la fenetre le tableau charge les animaux de la base de données
        // et les affiche dans le tableau 
        AnimalDAO animaldao = new AnimalDAO();
        DefaultTableModel defaultTableModel = (DefaultTableModel) jtableanimal.getModel();
        defaultTableModel.addColumn("ID");
        defaultTableModel.addColumn("Espece");
        defaultTableModel.addColumn("Age");
        defaultTableModel.addColumn("Race");
        defaultTableModel.addColumn("Poids");
        defaultTableModel.addColumn("Couleur");
        defaultTableModel.addColumn("Vaccin");
        defaultTableModel.addColumn("Photo");
        defaultTableModel.addColumn("Autre");
        for (int i = 0; i < animaldao.AfficherAnimauxSansRefuge().size(); i++) {
            defaultTableModel.addRow(new Object[]{
                        animaldao.AfficherAnimauxSansRefuge().get(i).getId(),
                        animaldao.AfficherAnimauxSansRefuge().get(i).getEspece(),
                        animaldao.AfficherAnimauxSansRefuge().get(i).getAge(),
                        animaldao.AfficherAnimauxSansRefuge().get(i).getRace(),
                        animaldao.AfficherAnimauxSansRefuge().get(i).getPoids(),
                        animaldao.AfficherAnimauxSansRefuge().get(i).getCouleur(),
                        animaldao.AfficherAnimauxSansRefuge().get(i).getVaccin(),
                        animaldao.AfficherAnimauxSansRefuge().get(i).getPhoto(),
                        animaldao.AfficherAnimauxSansRefuge().get(i).getAutre()});
        }
        jtableanimal.setModel(defaultTableModel);



    }//GEN-LAST:event_formWindowOpened

    private void ButtonAdopterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAdopterMouseClicked
        
        int row = jtableanimal.getSelectedRow();
        if (row==-1)
        {
             JOptionPane.showMessageDialog(null, "Vous devez selectionner un animal");
        }
        AnimalDAO andao = new AnimalDAO();
        int id_animal =(Integer.valueOf(jtableanimal.getModel().getValueAt(row,0).toString()));
        andao.ModifierEtatAnimal(1, id_animal); // ajouter la variable qui récupére l'id de l'utilisateur lors de sa connexion

    }//GEN-LAST:event_ButtonAdopterMouseClicked

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InterfaceAdopterAnimal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdopter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableanimal;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
