/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SOSAnimauxEspaceAdmin.java
 *
 * Created on 14 févr. 2014, 13:17:12
 */
package sos;

import Dao.AnimalDAO;
import Dao.DaoInt;
import Dao.Daopension;
import Dao.PrestataireDAO;
import Entities.Animal;
import Entities.Pension;
import Entities.Prestataire;
import Entities.adherant;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.application.Action;
import org.jfree.chart.ChartPanel;
import statistiques.PieChartEtatAnimal;
import statistiques.PieChartSexeAdherants;
import java.io.*;
import javax.net.ssl.*;
import java.net.UnknownHostException;
import java.util.Properties;
import javax.mail.Address;
import javax.mail.BodyPart;
import javax.mail.Folder;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.Session;
import javax.mail.Store;
import javax.swing.DefaultListModel;
import javax.swing.JProgressBar;
import statistiques.BarChartVaccin;

/**
 *
 * @author user
 */
public class SOSEspaceAdmin extends javax.swing.JFrame {
private static int tempValue=-1;
    JProgressBar progressBar;
    public static int idc;
    public static adherant usr;
    public static Prestataire pres;

    /** Creates new form SOSAnimauxEspaceAdmin */
    public SOSEspaceAdmin(int idc) {
        SOSEspaceAdmin.idc = idc;

        initComponents();

        addusertotable();
        chargmentStatistique();

        GestionPrestataire();
        afficheranimauxOnOpen();


        
//        getmail();


List <Prestataire> listprest =new ArrayList<Prestataire>();
        PrestataireDAO pDAO = new PrestataireDAO();
        Prestataire p = new Prestataire();
        DefaultListModel model = new DefaultListModel();
        jList1.setModel(model);
        listprest= pDAO.getALLPrestataireByDomaine("pensionnaire");
        for (int i = 0; i < listprest.size(); i++) {
            String nom = listprest.get(i).getNom();
            String prenom= listprest.get(i).getPrenom();
            String ch= nom + " " + prenom ;
            model.addElement(ch);
            jList1.updateUI();
            System.out.println("item ajouté");
        }






    }

    private SOSEspaceAdmin() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanelSexe = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanelEtat = new javax.swing.JPanel();
        jPanelVaccin = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtableanimal = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtespeceanimal = new javax.swing.JTextField();
        txtageanimal = new javax.swing.JTextField();
        txtraceanimal = new javax.swing.JTextField();
        txtpoidsanimal = new javax.swing.JTextField();
        txtcouleuranimal = new javax.swing.JTextField();
        txtvaccinanimal = new javax.swing.JTextField();
        txtetatanimal = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtautreanimal = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        txtnomanimal = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableadh = new javax.swing.JTable();
        jSeparator5 = new javax.swing.JSeparator();
        supprimer = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        supprimer1 = new javax.swing.JButton();
        modifier1 = new javax.swing.JButton();
        ajouter1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sos.SOSApp.class).getContext().getResourceMap(SOSEspaceAdmin.class);
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jTabbedPane1.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, resourceMap.getFont("jTabbedPane1.border.titleFont"), resourceMap.getColor("jTabbedPane1.border.titleColor"))); // NOI18N
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText(resourceMap.getString("jTabbedPane1.toolTipText")); // NOI18N
        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jPanel8.setBackground(resourceMap.getColor("jPanel8.background")); // NOI18N
        jPanel8.setName("jPanel8"); // NOI18N

        jPanelSexe.setName("jPanelSexe"); // NOI18N

        javax.swing.GroupLayout jPanelSexeLayout = new javax.swing.GroupLayout(jPanelSexe);
        jPanelSexe.setLayout(jPanelSexeLayout);
        jPanelSexeLayout.setHorizontalGroup(
            jPanelSexeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );
        jPanelSexeLayout.setVerticalGroup(
            jPanelSexeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jLabel16.setFont(resourceMap.getFont("jLabel16.font")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        jPanelEtat.setName("jPanelEtat"); // NOI18N

        javax.swing.GroupLayout jPanelEtatLayout = new javax.swing.GroupLayout(jPanelEtat);
        jPanelEtat.setLayout(jPanelEtatLayout);
        jPanelEtatLayout.setHorizontalGroup(
            jPanelEtatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );
        jPanelEtatLayout.setVerticalGroup(
            jPanelEtatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jPanelVaccin.setName("jPanelVaccin"); // NOI18N

        javax.swing.GroupLayout jPanelVaccinLayout = new javax.swing.GroupLayout(jPanelVaccin);
        jPanelVaccin.setLayout(jPanelVaccinLayout);
        jPanelVaccinLayout.setHorizontalGroup(
            jPanelVaccinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );
        jPanelVaccinLayout.setVerticalGroup(
            jPanelVaccinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jLabel17.setFont(resourceMap.getFont("jLabel17.font")); // NOI18N
        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jPanelEtat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jPanelVaccin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel17)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelVaccin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                                .addComponent(jPanelSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelEtat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jPanel6.setBackground(resourceMap.getColor("jPanel6.background")); // NOI18N
        jPanel6.setName("jPanel6"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sos.SOSApp.class).getContext().getActionMap(SOSEspaceAdmin.class, this);
        jButton3.setAction(actionMap.get("ajout")); // NOI18N
        jButton3.setFont(resourceMap.getFont("jButton3.font")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        jtableanimal.setFont(resourceMap.getFont("jtableanimal.font")); // NOI18N
        jtableanimal.setForeground(resourceMap.getColor("jtableanimal.foreground")); // NOI18N
        jtableanimal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtableanimal.setName("jtableanimal"); // NOI18N
        jtableanimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableanimalMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jtableanimal);

        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N

        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N

        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N

        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N

        jLabel23.setText(resourceMap.getString("jLabel23.text")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N

        jLabel24.setText(resourceMap.getString("jLabel24.text")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N

        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N

        jLabel26.setText(resourceMap.getString("jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N

        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N

        txtespeceanimal.setText(resourceMap.getString("txtespeceanimal.text")); // NOI18N
        txtespeceanimal.setName("txtespeceanimal"); // NOI18N

        txtageanimal.setText(resourceMap.getString("txtageanimal.text")); // NOI18N
        txtageanimal.setName("txtageanimal"); // NOI18N

        txtraceanimal.setText(resourceMap.getString("txtraceanimal.text")); // NOI18N
        txtraceanimal.setName("txtraceanimal"); // NOI18N

        txtpoidsanimal.setText(resourceMap.getString("txtpoidsanimal.text")); // NOI18N
        txtpoidsanimal.setName("txtpoidsanimal"); // NOI18N

        txtcouleuranimal.setText(resourceMap.getString("txtcouleuranimal.text")); // NOI18N
        txtcouleuranimal.setName("txtcouleuranimal"); // NOI18N

        txtvaccinanimal.setText(resourceMap.getString("txtvaccinanimal.text")); // NOI18N
        txtvaccinanimal.setName("txtvaccinanimal"); // NOI18N

        txtetatanimal.setText(resourceMap.getString("txtetatanimal.text")); // NOI18N
        txtetatanimal.setName("txtetatanimal"); // NOI18N

        jScrollPane6.setName("jScrollPane6"); // NOI18N

        txtautreanimal.setColumns(20);
        txtautreanimal.setRows(5);
        txtautreanimal.setName("txtautreanimal"); // NOI18N
        jScrollPane6.setViewportView(txtautreanimal);

        jButton8.setFont(resourceMap.getFont("jButton8.font")); // NOI18N
        jButton8.setText(resourceMap.getString("jButton8.text")); // NOI18N
        jButton8.setName("jButton8"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(resourceMap.getFont("jButton9.font")); // NOI18N
        jButton9.setText(resourceMap.getString("jButton9.text")); // NOI18N
        jButton9.setName("jButton9"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        txtnomanimal.setText(resourceMap.getString("txtnomanimal.text")); // NOI18N
        txtnomanimal.setName("txtnomanimal"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnomanimal)
                            .addComponent(txtetatanimal)
                            .addComponent(txtvaccinanimal)
                            .addComponent(txtcouleuranimal)
                            .addComponent(txtpoidsanimal)
                            .addComponent(txtraceanimal)
                            .addComponent(txtageanimal)
                            .addComponent(txtespeceanimal)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton3)
                .addGap(209, 209, 209)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtnomanimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtespeceanimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtageanimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtraceanimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtpoidsanimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txtcouleuranimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtvaccinanimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtetatanimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel27))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addContainerGap())
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel6.TabConstraints.tabTitle"), jPanel6); // NOI18N

        jPanel9.setBackground(resourceMap.getColor("jPanel9.background")); // NOI18N
        jPanel9.setName("jPanel9"); // NOI18N

        jSeparator4.setName("jSeparator4"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "De", "Date", "Sujet", "Objet"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setName("jTable3"); // NOI18N
        jScrollPane3.setViewportView(jTable3);
        jTable3.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTable3.columnModel.title0")); // NOI18N
        jTable3.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTable3.columnModel.title1")); // NOI18N
        jTable3.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTable3.columnModel.title2")); // NOI18N
        jTable3.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("jTable3.columnModel.title3")); // NOI18N

        jButton7.setFont(resourceMap.getFont("jButton7.font")); // NOI18N
        jButton7.setText(resourceMap.getString("jButton7.text")); // NOI18N
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton5.setFont(resourceMap.getFont("jButton5.font")); // NOI18N
        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1062, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton5))
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel9.TabConstraints.tabTitle"), jPanel9); // NOI18N

        jPanel10.setBackground(resourceMap.getColor("jPanel10.background")); // NOI18N
        jPanel10.setName("jPanel10"); // NOI18N

        jLabel18.setFont(resourceMap.getFont("jLabel18.font")); // NOI18N
        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        jSeparator3.setName("jSeparator3"); // NOI18N

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        jTableadh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nom", "prenom", "age", "sexe", "adresse", "ville", "mail", "telephone"
            }
        ));
        jTableadh.setName("jTableadh"); // NOI18N
        jScrollPane4.setViewportView(jTableadh);

        jSeparator5.setName("jSeparator5"); // NOI18N

        supprimer.setFont(resourceMap.getFont("supprimer.font")); // NOI18N
        supprimer.setText(resourceMap.getString("supprimer.text")); // NOI18N
        supprimer.setName("supprimer"); // NOI18N
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        modifier.setFont(resourceMap.getFont("modifier.font")); // NOI18N
        modifier.setText(resourceMap.getString("modifier.text")); // NOI18N
        modifier.setName("modifier"); // NOI18N
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        ajouter.setFont(resourceMap.getFont("ajouter.font")); // NOI18N
        ajouter.setText(resourceMap.getString("ajouter.text")); // NOI18N
        ajouter.setName("ajouter"); // NOI18N
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259)
                .addComponent(supprimer)
                .addGap(67, 67, 67))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(458, 458, 458)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(383, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouter)
                    .addComponent(modifier)
                    .addComponent(supprimer)))
        );

        jTabbedPane1.addTab("Espace adherant", jPanel10);

        jPanel4.setBackground(resourceMap.getColor("jPanel4.background")); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel2FocusLost(evt);
            }
        });

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new sos.gui.TableModelAfficheEditAllPensions());
        jTable1.setName("jTable1"); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jSeparator2.setName("jSeparator2"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jList1.setName("jList1"); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jButton6.setFont(resourceMap.getFont("jButton6.font")); // NOI18N
        jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(370, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(186, 186, 186)
                .addComponent(jLabel2)
                .addGap(123, 123, 123))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton4)))
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                        .addGap(97, 97, 97))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(46, 46, 46)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(741, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(544, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(43, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel4.TabConstraints.tabTitle"), jPanel4); // NOI18N

        jPanel3.setBackground(resourceMap.getColor("jPanel3.background")); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        jPanel5.setName("jPanel5"); // NOI18N

        jScrollPane7.setName("jScrollPane7"); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setName("jTable2"); // NOI18N
        jScrollPane7.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        supprimer1.setFont(resourceMap.getFont("supprimer1.font")); // NOI18N
        supprimer1.setText(resourceMap.getString("supprimer1.text")); // NOI18N
        supprimer1.setName("supprimer1"); // NOI18N
        supprimer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimer1ActionPerformed(evt);
            }
        });

        modifier1.setFont(resourceMap.getFont("modifier1.font")); // NOI18N
        modifier1.setText(resourceMap.getString("modifier1.text")); // NOI18N
        modifier1.setName("modifier1"); // NOI18N
        modifier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifier1ActionPerformed(evt);
            }
        });

        ajouter1.setFont(resourceMap.getFont("ajouter1.font")); // NOI18N
        ajouter1.setText(resourceMap.getString("ajouter1.text")); // NOI18N
        ajouter1.setName("ajouter1"); // NOI18N
        ajouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(supprimer1)
                .addGap(244, 244, 244)
                .addComponent(modifier1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                .addComponent(ajouter1)
                .addGap(125, 125, 125))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supprimer1)
                    .addComponent(modifier1)
                    .addComponent(ajouter1)))
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        String expediteur = "";
        String dateex = "";
        String sujet = "";
        String message = "";

        if (jTable3.getSelectedRow() != -1) {
            expediteur = (String) jTable3.getModel().getValueAt(jTable3.getSelectedRow(), 0);

            sujet = (String) jTable3.getModel().getValueAt(jTable3.getSelectedRow(), 2);
            message = (String) jTable3.getModel().getValueAt(jTable3.getSelectedRow(), 3);


            Lireemail lireemail = new Lireemail(expediteur, sujet, message);
            lireemail.setVisible(true);

        } else {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "Veuillez selectionnez une ligne", "SOS Animaux - Attention", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed


        if (jTableadh.getSelectedRow() != -1) {
            int id = (Integer) jTableadh.getModel().getValueAt(jTableadh.getSelectedRow(), 0);
            DaoInt daop = new DaoInt();
            adherant p1 = daop.getById(id);
            daop.delete(p1);
            //mettre a jour le modele de la table
            DefaultTableModel defaultTableModel = (DefaultTableModel) jTableadh.getModel();
            defaultTableModel.removeRow(jTableadh.getSelectedRow());
            jTableadh.setModel(defaultTableModel);
            jTableadh.repaint();
        } else {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "Veuillez selectionnez une ligne", "SOS Animaux - Attention", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_supprimerActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        if (jTableadh.getSelectedRow() != -1) {
            int id = (Integer) jTableadh.getModel().getValueAt(jTableadh.getSelectedRow(), 0);
            DaoInt aOUser = new DaoInt();
            usr = aOUser.getById(id);
            ModifierUser m = new ModifierUser();
            m.setVisible(true);
            //setVisible(false);
        } else {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "Veuillez selectionnez une ligne", "SOS Animaux - Attention", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_modifierActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        InsertionUser p = new InsertionUser();
        p.setVisible(true);
}//GEN-LAST:event_ajouterActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // recupérer la ligne selectionner dans le tableau
        // recupérer le champ id et appler la méthode supprimer animal
        if (jtableanimal.getSelectedRow() != -1) {
            int row = jtableanimal.getSelectedRow();
            AnimalDAO andao = new AnimalDAO();
            int id_animal = (Integer.valueOf(jtableanimal.getModel().getValueAt(row, 0).toString()));
            andao.SupprimerAnimal(id_animal);
            DefaultTableModel animaux = (DefaultTableModel) jtableanimal.getModel();
            animaux.removeRow(jtableanimal.getSelectedRow());
            jtableanimal.setModel(animaux);
            jtableanimal.repaint();
            txtnomanimal.setText("");
            txtespeceanimal.setText("");
            txtageanimal.setText("");
            txtraceanimal.setText("");
            txtpoidsanimal.setText("");
            txtcouleuranimal.setText("");
            txtvaccinanimal.setText("");
            txtetatanimal.setText("");
            txtautreanimal.setText("");


        } else {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "Veuillez selectionnez une ligne", "SOS Animaux - Attention", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int row = jtableanimal.getSelectedRow();

        Animal animal = new Animal();
        animal.setId(Integer.valueOf(jtableanimal.getModel().getValueAt(row, 0).toString()));
        animal.setNom(txtnomanimal.getText().toString());
        animal.setEspece(txtespeceanimal.getText().toString());
        animal.setAge(txtageanimal.getText().toString());
        animal.setRace(txtraceanimal.getText().toString());
        animal.setPoids(txtpoidsanimal.getText().toString());
        animal.setCouleur(txtcouleuranimal.getText().toString());
        animal.setVaccin(txtvaccinanimal.getText().toString());
        animal.setEtat(txtetatanimal.getText().toString());
        animal.setAutre(txtautreanimal.getText().toString());

        AnimalDAO andao = new AnimalDAO();
        andao.MiseAjourAnimal(animal);
        JOptionPane.showMessageDialog(null, "Modification terminée avec succées");
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jtableanimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableanimalMouseClicked
        // recupérer la ligne selectionnée
        int row = jtableanimal.getSelectedRow();
        txtnomanimal.setText(jtableanimal.getModel().getValueAt(row, 1).toString());
        txtespeceanimal.setText(jtableanimal.getModel().getValueAt(row, 2).toString());
        txtageanimal.setText(jtableanimal.getModel().getValueAt(row, 3).toString());
        txtraceanimal.setText(jtableanimal.getModel().getValueAt(row, 4).toString());
        txtpoidsanimal.setText(jtableanimal.getModel().getValueAt(row, 5).toString());
        txtcouleuranimal.setText(jtableanimal.getModel().getValueAt(row, 6).toString());
        txtvaccinanimal.setText(jtableanimal.getModel().getValueAt(row, 7).toString());
        txtetatanimal.setText(jtableanimal.getModel().getValueAt(row, 8).toString());
        txtautreanimal.setText(jtableanimal.getModel().getValueAt(row, 9).toString());
    }//GEN-LAST:event_jtableanimalMouseClicked

    private void jPanel2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusLost
        // TODO add your handling code here:
}//GEN-LAST:event_jPanel2FocusLost

    private void jPanel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusGained

}//GEN-LAST:event_jPanel2FocusGained

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
}//GEN-LAST:event_jButton6ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if(evt.getClickCount()==2) {
            System.out.println("TEMP "+tempValue);
            if(tempValue!=-1) {
                jTable1.setValueAt(jList1.getSelectedValue().toString(),tempValue, 4);

                TableModelAfficheEditAllPensions tb = new TableModelAfficheEditAllPensions();
                jTable1.setModel(tb);
                tb.fireTableDataChanged();


            }else {
                JOptionPane.showMessageDialog(null, "Selectionnez le Pensionnaire que vous désiriez affecter à la pension");
            }

        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Suppression d'un ou plusieurs éléments de la jtable
        Pension p = new Pension();

        boolean test= false;     //TESTER SI'IL Y A DES ELEMENTS COCHés
        for(int i=0;i<jTable1.getRowCount();i++) {
            Boolean a =(Boolean)jTable1.getValueAt(i, 5);
            if(a) {
                test=true;
                break; }

        }

        if(test) // s'il y a des éléments
        {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            JOptionPane.showConfirmDialog(null, "Voulez vous supprimer toutes les pensions selectionnés?","Warning",dialogButton);  // confirmation ?

            if(dialogButton == JOptionPane.YES_OPTION){


                Daopension pDAO = new Daopension();

                int ids[]=new int[50];
                int j=-1;

                for(int i=0;i<jTable1.getRowCount();i++) {
                    Boolean b =(Boolean)jTable1.getValueAt(i, 5);

                    if(b) {
                        j++;
                        ids[j]=(int) pDAO.getIdFromName(jTable1.getValueAt(i, 0).toString()) ;
                    }

                }

                while(j!=-1) {
                    pDAO.deletePension(ids[j]);
                    System.out.println("element supprimé "+j);
                    j--;
                }
                TableModelAfficheEditAllPensions  model = new TableModelAfficheEditAllPensions();
                jTable1.setModel(model);
                jTable1.getColumnModel().getColumn(0).setMinWidth(0);
                jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            }
        } else {
            int diag = JOptionPane.PLAIN_MESSAGE;
            JOptionPane.showConfirmDialog(null, "Aucun élément sélectionné !","Warning",diag);


        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Ajout
        new interfaceAjoutPension().show();
}//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if(evt.getKeyCode()==10) {

            TableModelAfficheEditAllPensions tb = new TableModelAfficheEditAllPensions();
            jTable1.setModel(tb);
            tb.fireTableDataChanged();

        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        tempValue=jTable1.getSelectedRow();

        // TODO add your handling code here:
}//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FacturePension facturepens = new FacturePension();
        facturepens.setVisible(true);
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 progressBar = new JProgressBar(0, 5000);
progressBar.setValue(0);
progressBar.setStringPainted(true);
        getmail();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void supprimer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimer1ActionPerformed
       if (jTable2.getSelectedRow() != -1) {
            //id selectionner du tableau
            int id = (Integer) jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 0);
            PrestataireDAO daop = new PrestataireDAO();
            //retourner lobjet avec son id
            Prestataire p1 = daop.getById(id);
            //suppresion de l objet
            daop.delete(p1);
            //mettre a jour le modele de la table apres suppression
            DefaultTableModel defaultTableModel = (DefaultTableModel) jTable2.getModel();
            defaultTableModel.removeRow(jTable2.getSelectedRow());
            jTable2.setModel(defaultTableModel);
            jTable2.repaint();
        } else {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "Veuillez selectionnez une ligne", "SOS Animaux - Attention", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_supprimer1ActionPerformed

    private void modifier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifier1ActionPerformed
if (jTable2.getSelectedRow() != -1) {
            //id selectionner du tableau
            int id = (Integer) jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 0);
            PrestataireDAO aOPrestataire = new PrestataireDAO();
            //retrouner l objet avec l id selectionner
            pres = aOPrestataire.getById(id);
            ModifierPrestataire modifierPrestataire = new ModifierPrestataire();
            modifierPrestataire.setVisible(true);
            
        } else {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "Veuillez selectionnez une ligne", "SOS Animaux - Attention", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modifier1ActionPerformed

    private void ajouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter1ActionPerformed
        InserttionPrestataire p = new InserttionPrestataire();
        p.setVisible(true);

    }//GEN-LAST:event_ajouter1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SOSEspaceAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton ajouter1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelEtat;
    private javax.swing.JPanel jPanelSexe;
    private javax.swing.JPanel jPanelVaccin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTableadh;
    private javax.swing.JTable jtableanimal;
    private javax.swing.JButton modifier;
    private javax.swing.JButton modifier1;
    private javax.swing.JButton supprimer;
    private javax.swing.JButton supprimer1;
    private javax.swing.JTextField txtageanimal;
    private javax.swing.JTextArea txtautreanimal;
    private javax.swing.JTextField txtcouleuranimal;
    private javax.swing.JTextField txtespeceanimal;
    private javax.swing.JTextField txtetatanimal;
    private javax.swing.JTextField txtnomanimal;
    private javax.swing.JTextField txtpoidsanimal;
    private javax.swing.JTextField txtraceanimal;
    private javax.swing.JTextField txtvaccinanimal;
    // End of variables declaration//GEN-END:variables

    

    



    @Action
    public void ajout() {
        System.out.println(idc);
        ajoutanimal ajouts = new ajoutanimal();

        ajouts.setVisible(true);


    }

    private void chargmentStatistique() {

        //Charger les statistiques de la répartition des sexes des adhérants
        ChartPanel chSexe = new ChartPanel(PieChartSexeAdherants.createChart("Adhérants: Homme | Femme"));
        chSexe.setBounds(0, 0, (int) jPanelSexe.getSize().getWidth(), (int) jPanelSexe.getSize().getHeight());
        jPanelSexe.add(chSexe);
        jPanelSexe.repaint();

        //Charger les statistiques de la répartition des etats des animaux
        ChartPanel chEtatAnimal = new ChartPanel(PieChartEtatAnimal.createChart("Etats des animaux"));
        chEtatAnimal.setBounds(0, 0, (int) jPanelEtat.getSize().getWidth(), (int) jPanelEtat.getSize().getHeight());
        jPanelEtat.add(chEtatAnimal);
        jPanelEtat.repaint();

        //Charger les statistiques de la répartition des animaux vaccinés | non vaccinés
        ChartPanel chVaccinAnimal = new ChartPanel(BarChartVaccin.createChart("Vaccination"));
        chVaccinAnimal.setBounds(0, 0, (int) jPanelVaccin.getSize().getWidth(), (int) jPanelVaccin.getSize().getHeight());
        jPanelVaccin.add(chVaccinAnimal);
        jPanelVaccin.repaint();

    }

    public void getmail() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable3.getModel();
        Properties props = new Properties();
        props.setProperty("mail.store.protocol", "imaps");
        try {
            Session session = Session.getInstance(props, null);
            Store store = session.getStore();
            store.connect("imap.gmail.com", "sosanimauxtunisia@gmail.com", "sosanimaux.@");
            Folder inbox = store.getFolder("INBOX");
            inbox.open(Folder.READ_ONLY);
            System.out.println("hoooooooooooooooooo");
            for (int i = 1; i <= inbox.getMessageCount(); i++) {

                Message msg = inbox.getMessage(i);
                Address[] in = msg.getFrom();
                for (Address address : in) {

                    System.out.println("FROM:" + address.toString());

                    Multipart mp = (Multipart) msg.getContent();
                    BodyPart bp = mp.getBodyPart(0);
                    System.out.println("SENT DATE:" + msg.getSentDate());
                    System.out.println("SUBJECT:" + msg.getSubject());

                    System.out.println("CONTENT:" + bp.getContent());
                    defaultTableModel.addRow(new Object[]{address.toString(), msg.getSentDate(), msg.getSubject(), bp.getContent()});
                }
            }
        } catch (Exception mex) {
            mex.printStackTrace();
        }
    }

    public void addusertotable() {
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        List<adherant> Users = new ArrayList<adherant>();
        DaoInt d = new DaoInt();
        Users = d.getAll();
        defaultTableModel.addColumn("id");
        defaultTableModel.addColumn("nom");
        defaultTableModel.addColumn("prenom");
        defaultTableModel.addColumn("age");
        defaultTableModel.addColumn("sexe");
        defaultTableModel.addColumn("adresse");
        defaultTableModel.addColumn("ville");
        defaultTableModel.addColumn("mail");
        defaultTableModel.addColumn("telephone");
        //defaultTableModel.addColumn("mot de passe");



        for (adherant p : Users) {
            defaultTableModel.addRow(new Object[]{p.getId(), p.getNom(), p.getPrenom(), p.getAge(), p.getSexe(), p.getAdresse(), p.getVille(), p.getEmail(), p.getTelephone()});
        }
        jTableadh.setModel(defaultTableModel);

    }

    public void afficheranimauxOnOpen() {  // lors de l'ouverture de la fenetre le tableau charge les animaux de la base de données
        // et les affiche dans le tableau
        AnimalDAO animaldao = new AnimalDAO();

        DefaultTableModel defaultTableModel = (DefaultTableModel) jtableanimal.getModel();
        defaultTableModel.addColumn("ID");
        defaultTableModel.addColumn("Nom");
        defaultTableModel.addColumn("Espece");
        defaultTableModel.addColumn("Age");
        defaultTableModel.addColumn("Race");
        defaultTableModel.addColumn("Poids");
        defaultTableModel.addColumn("Couleur");
        defaultTableModel.addColumn("Vaccin");
        defaultTableModel.addColumn("Etat");
        defaultTableModel.addColumn("Autre");
        for (int i = 0; i < animaldao.AfficherAnimaux().size(); i++) {
            defaultTableModel.addRow(new Object[]{
                        animaldao.AfficherAnimaux().get(i).getId(),
                        animaldao.AfficherAnimaux().get(i).getNom(),
                        animaldao.AfficherAnimaux().get(i).getEspece(),
                        animaldao.AfficherAnimaux().get(i).getAge(),
                        animaldao.AfficherAnimaux().get(i).getRace(),
                        animaldao.AfficherAnimaux().get(i).getPoids(),
                        animaldao.AfficherAnimaux().get(i).getCouleur(),
                        animaldao.AfficherAnimaux().get(i).getVaccin(),
                        animaldao.AfficherAnimaux().get(i).getEtat(),
                        animaldao.AfficherAnimaux().get(i).getAutre()});
        }
        jtableanimal.setModel(defaultTableModel);

    }

    public void GestionPrestataire() {
        
        
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        List<Prestataire> prestataires = new ArrayList<Prestataire>();
        PrestataireDAO d =new PrestataireDAO();
        prestataires = d.getAll();
        defaultTableModel.addColumn("Id");
        defaultTableModel.addColumn("Nom");
        defaultTableModel.addColumn("Prenom");
        defaultTableModel.addColumn("Adresse");
        defaultTableModel.addColumn("Domaine");
        for (Prestataire p : prestataires) {
            defaultTableModel.addRow(new Object[]{p.getId(), p.getNom(), p.getPrenom(), p.getAdresse(), p.getDomaine()});
        }
        jTable2.setModel(defaultTableModel);



    }












}
