

package sos.gui;

import Dao.PrestataireDAO;
import Entities.Prestataire;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


/**
 *
 * @author Lenovo
 */
public class InterfaceAfficheMétiersAnimaliers extends javax.swing.JFrame {
     List <Prestataire> prestSelect =new ArrayList<Prestataire>(); //contient tt les prestataires séléctionnées

    /** Creates new form InterfaceAfficheMétiersAnimaliers */
    public InterfaceAfficheMétiersAnimaliers() {
        initComponents();

         PrestataireDAO prestDAO = new PrestataireDAO();
          List <String> listdomaine =new ArrayList<String>();
          Vector comboBoxItems=new Vector();

                listdomaine = prestDAO.getDistinctPrestataireDomaine();
                System.out.println("TAILLE "+listdomaine.size());
                for (int i=0; i<listdomaine.size();i++) {
                        comboBoxItems.add(listdomaine.get(i));
                   System.out.println(listdomaine.get(i));

                }
         final DefaultComboBoxModel model = new DefaultComboBoxModel(comboBoxItems);
         jComboBox1.setModel(model);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Nos Services offerts:");

        jTable1.setModel(new TableModelAfficheMétiersAnimaliers());
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Somme Approximative des prix des services sélectionnés");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1)
                .addContainerGap(284, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         String x =jComboBox1.getSelectedItem().toString();


        if(x!="")
   { System.out.println("x= "+x);
     TableModelAfficheMétiersAnimaliers tb = new TableModelAfficheMétiersAnimaliers(x);
                jTable1.setModel(tb);
                tb.fireTableDataChanged();

   }







    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed

         if(evt.getKeyCode()==10)
    {


          boolean test= false;     //TESTER SI'IL Y A DES ELEMENTS COCHés
                for(int i=0;i<jTable1.getRowCount();i++)
                    {
                        Boolean a =(Boolean)jTable1.getValueAt(i,4);
                        if(a)
                        { test=true;
                          break; }

                      }

      if(test) // s'il y a des éléments
       {
         int dialogButton = JOptionPane.YES_NO_OPTION;
         JOptionPane.showConfirmDialog (null, "Ajouter au panier?","Warning",dialogButton);  // confirmation ?

                if(dialogButton == JOptionPane.YES_OPTION){

                     PrestataireDAO pDAO= new PrestataireDAO();
                     
                     int j=-1 ;

                    for(int i=0; i<jTable1.getRowCount(); i++)
                    {
                        Boolean b =(Boolean)jTable1.getValueAt(i, 4);

                        if(b)
                        {  j++;
                           Prestataire p = new Prestataire(); //Current prestataire sélectionné
                           p.setPrix_serv((Double)jTable1.getValueAt(i,3)) ;
                           p.setId(pDAO.getIDPrestataireByName(jTable1.getValueAt(i,0).toString()));
                           prestSelect.add(p);
                        }

                    }

                }
           //System.out.println("taille de prestSelect= "+prestSelect.size());
          double somme = 0;
           //System.out.println("Prix dans PRESTSELECT= ");
          for(int i=0; i<prestSelect.size(); i++){
              //System.out.println("prix n° :"+i+"  "+prestSelect.get(i).getPrix_serv());
              double nb = prestSelect.get(i).getPrix_serv();
              somme=somme+nb;
              String ch= String.valueOf(somme)+"dt";
               jTextField1.setText(ch);
          }
           System.out.println("La somme de tt les services= "+somme);

       }


          


     /*  else
       {
            int diag = JOptionPane.PLAIN_MESSAGE;
                JOptionPane.showConfirmDialog (null, "Sélectionner un service !","Warning",diag);


       } */


         }
    }//GEN-LAST:event_jTable1KeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceAfficheMétiersAnimaliers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
